name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: foxy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.3
        with:
          package-name: follow_wall_l4ros2
          import-token: ${{secrets.GITHUB_TOKEN}}
          target-ros2-distro: foxy
          colcon-defaults: |
        {
          "test": {
            "ctest-args": [
                "-LE copyright"
            ]
          }
        }
      - name: Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: false
